### ISSUE TITLE
색상 Theme

### ISSUE THREAD

**Issue by uxdx** [uxdx/blog#2]
```scss
const dark_theme = {
    primary: "#000",
    p_light: "#232323",
    p_dark: "#1b1b1b",
    on_p: "#fafafa",
    secondary: "#4a148c",
    s_light: "#7c43bd",
    s_dark: "#12005e",
    on_s: "#fff"
}
```
